### ISSUE TITLE
Update script to match the changes

### ISSUE THREAD

**Issue by alihaider1264** [alihaider1264/SCA#33]
- update the script to match the new dir structure
- delete script folder once done
- Driver.cpp/Unit Tests should run when the installation completes.
- move /ANTLR outside to root folder.

**Comment by alihaider1264** [comment]
Looks good. Merged. I will run it on Ubuntu in the morning and provide feedback. You can also try and run the script to see if it works.

**Comment by alihaider1264** [comment]
I am getting the following error when I run the script

~/Documents/SCA-Prod$ ./install_SCA_ubuntu.sh 
./install_SCA_ubuntu.sh: line 7: syntax error near unexpected token `newline'
./install_SCA_ubuntu.sh: line 7: `<!DOCTYPE html>'

**Comment by alihaider1264** [comment]
I was able to install the system. The problem was in downloading the shell file. I downloaded it raw and it worked. Some issues with test files though. Let me know how is goes when you guys run it @itstockra @Harrison7318 @itDingle

**Comment by itstockra** [comment]
I believe the /user/output folder is not there because when we clone the repo any empty folders are not added to the users file system.. I can add another line in the script to account for this (add the directory /user/output if it's not already created from the git clone)

**Comment by alihaider1264** [comment]
Yes. That is a good idea. We need to enforce our dir structure.
