### ISSUE TITLE
Rules.txt - all additions

### ISSUE THREAD

**Issue by alihaider1264** [alihaider1264/SCA#34]
- Add more rules to rules.txt
- update matchTemplateTable.h to cover the use-discussed today i.e., for(int i=0;i<10;I++) @Harrison7318 
- Propose at least 5 new rules in comments.

**Comment by itDingle** [comment]
Checking that while loop conditions rely on a variable within the wile loop. For example,

while(variable < 5)
{
   otherVariable++;
}

should be recognized and suggested that a variable used in a while loop condition ought to be modified within the while loop so it may meet the condition

**Comment by itDingle** [comment]
Similar to rules 3 and 4, should be a rule for "unqualifiedID = unqualified ID - 1" suggesting variable--, or additionally "unqualifiedID = unqualifiedID +/- number" can be suggested for using "unqualifiedID +=/-= number"

**Comment by itstockra** [comment]
Rules for uninitialized variables:
49,3,int unqualifiedId ;, Make sure you initialize your variables when they are declared.
50,3,double unqaulifiedId ;,Make sure you initialize your variables when they are declared.
51,3,char unqaulifiedId ;,Make sure you initialize your variables when they are declared.
52,3,string unqaulifiedId ;,Make sure you initialize your variables when they are declared.
53,3,float unqaulifiedId ;,Make sure you initialize your variables when they are declared.
54,3,bool unqaulifiedId ;,Make sure you initialize your variables when they are declared.

Switch Structures: (check for 'break' statement in each case, and make sure there is a default case)
switch(someVar) {
   case 1:
      break;
   case 2:
      break;
   default:
      break;
}

Check if/else statements, if there is no body for the if statement suggest negating the if statement and dropping the else
Ex:
if (x == 4) {}
else { x++; }
Change to:
if (x != 4) { x++; }

If there are numerous if/else if/else if... statements suggest using a switch structure instead.
