### ISSUE TITLE
Print final messages for user

### ISSUE THREAD

**Issue by alihaider1264** [alihaider1264/SCA#37]
https://github.com/alihaider1264/SCA/blob/f07b3d0ad612ad5f327496947cd1ec5f6145ccdb/script/install_SCA_ubuntu.sh#L60

Good work on the script. It installs smoothly.

Once the script finishes and driver finishes execution, print a message that shows path for source files and path for html files. If we can open the html file in the browser, that will be super. 
i.e.,

How to run the system:
Load user source files in the folder: ~/SCA/SCA/user/source-code
go to ~/SCA/SCA/core/src/
and run
g++ Driver.cpp
See output as HTML files in 
~/SCA/SCA/user/output

**Comment by itstockra** [comment]
Do you want the Driver.cpp to automatically open the .html files produced by running the a.out file? For instance, after the Driver.cpp runs through the files in /source-code and produces all the .html files in /output have it run through each file in /output and open a browser tab for each .html file?

**Comment by alihaider1264** [comment]
If that can be done, it will be great but if it will take too much time, don't worry about it.
Instead, we can only open the /output folder. This way we do not need to open HTML files in the browser. The user can open HTML files manually. 
At the least, we need to provide the path to the output folder.
